# Generated by Django 3.0.6 on 2020-05-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vencode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoters154cellsbinarized',
            options={'managed': True},
        ),
    ]
