# Generated by Django 3.0.6 on 2020-05-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vencode', '0002_auto_20200516_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoters154cellsbinarized',
            options={'managed': False},
        ),
    ]
